# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
objs = []

d = 'me'

path = os.path.join(cwd, d)
if os.path.isfile(os.path.join(path, 'SConscript')):
    objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
