Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('ev', src, depend = ['PKG_USING_EV'], CPPPATH = CPPPATH)

Return('group')
